### ISSUE TITLE
Failed to Build 

### ISSUE THREAD

**Issue by Munodiwa** [marjan-georgiev/Angular-CLI-ngx-charts-Demo#1]
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (C:\Users\mbore\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (C:\Users\mbore\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:24:21)
    at ServeCommand._loadWorkspaceAndArchitect (C:\Users\mbore\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:180:32)
    at ServeCommand.<anonymous> (C:\Users\mbore\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at C:\Users\mbore\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\mbore\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:3:12)
    at ServeCommand.initialize (C:\Users\mbore\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:46:16)
    at Object.<anonymous> (C:\Users\mbore\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js:87:23)

This is the error that comes up when I try to build the project. Please support me in this regard.

**Comment by marjan-georgiev** [comment]
what version of angular-cli are you using? Did you run `npm install` first?

**Comment by Munodiwa** [comment]
Thank you it works!
